// Code generated by iocli

package api

import (
	"github.com/alibaba/ioc-golang/autowire"
	"github.com/alibaba/ioc-golang/autowire/normal"
	"github.com/alibaba/ioc-golang/extension/autowire/rpc/rpc_client"
	"github.com/ioc-golang/shopping-system/pkg/model/dto"
)

func init() {
	rpc_client.RegisterStructDescriptor(&autowire.StructDescriptor{
		Factory: func() interface{} {
			return &serviceIOCRPCClient{}
		},
	})
	normal.RegisterStructDescriptor(&autowire.StructDescriptor{
		Factory: func() interface{} {
			return &serviceIOCRPCClient_{}
		},
	})
}

type serviceIOCRPCClient_ struct {
	ListCards_ func(pageIndex, pageSize int) ([]dto.Card, int, error)
}

func (s *serviceIOCRPCClient_) ListCards(pageIndex, pageSize int) ([]dto.Card, int, error) {
	return s.ListCards_(pageIndex, pageSize)
}

type ServiceIOCRPCClient interface {
	ListCards(pageIndex, pageSize int) ([]dto.Card, int, error)
}

type serviceIOCRPCClient struct {
	ListCards func(pageIndex, pageSize int) ([]dto.Card, int, error)
}
