// Code generated by iocli, run 'iocli gen' to re-generate

package api

import (
	"github.com/alibaba/ioc-golang/autowire"
	"github.com/alibaba/ioc-golang/autowire/normal"
	"github.com/alibaba/ioc-golang/extension/autowire/rpc/rpc_client"
)

func init() {
	rpc_client.RegisterStructDescriptor(&autowire.StructDescriptor{
		Factory: func() interface{} {
			return &serviceIOCRPCClient{}
		},
	})
	normal.RegisterStructDescriptor(&autowire.StructDescriptor{
		Factory: func() interface{} {
			return &serviceIOCRPCClient_{}
		},
	})
}

type serviceIOCRPCClient_ struct {
	GetRecommendProductIDs_ func(userID int64, num int) ([]int64, error)
}

func (s *serviceIOCRPCClient_) GetRecommendProductIDs(userID int64, num int) ([]int64, error) {
	return s.GetRecommendProductIDs_(userID, num)
}

type ServiceIOCRPCClient interface {
	GetRecommendProductIDs(userID int64, num int) ([]int64, error)
}

type serviceIOCRPCClient struct {
	GetRecommendProductIDs func(userID int64, num int) ([]int64, error)
}
