//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by iocli, run 'iocli gen' to re-generate

package auth

import (
	autowire "github.com/alibaba/ioc-golang/autowire"
	normal "github.com/alibaba/ioc-golang/autowire/normal"
	singleton "github.com/alibaba/ioc-golang/autowire/singleton"
	util "github.com/alibaba/ioc-golang/autowire/util"
)

func init() {
	normal.RegisterStructDescriptor(&autowire.StructDescriptor{
		Factory: func() interface{} {
			return &authenticator_{}
		},
	})
	authenticatorStructDescriptor := &autowire.StructDescriptor{
		Factory: func() interface{} {
			return &Authenticator{}
		},
		Metadata: map[string]interface{}{
			"aop":      map[string]interface{}{},
			"autowire": map[string]interface{}{},
		},
	}
	singleton.RegisterStructDescriptor(authenticatorStructDescriptor)
}

type authenticator_ struct {
	Check_ func(userID int64) bool
}

func (a *authenticator_) Check(userID int64) bool {
	return a.Check_(userID)
}

type AuthenticatorIOCInterface interface {
	Check(userID int64) bool
}

var _authenticatorSDID string

func GetAuthenticatorSingleton() (*Authenticator, error) {
	if _authenticatorSDID == "" {
		_authenticatorSDID = util.GetSDIDByStructPtr(new(Authenticator))
	}
	i, err := singleton.GetImpl(_authenticatorSDID, nil)
	if err != nil {
		return nil, err
	}
	impl := i.(*Authenticator)
	return impl, nil
}

func GetAuthenticatorIOCInterfaceSingleton() (AuthenticatorIOCInterface, error) {
	if _authenticatorSDID == "" {
		_authenticatorSDID = util.GetSDIDByStructPtr(new(Authenticator))
	}
	i, err := singleton.GetImplWithProxy(_authenticatorSDID, nil)
	if err != nil {
		return nil, err
	}
	impl := i.(AuthenticatorIOCInterface)
	return impl, nil
}

type ThisAuthenticator struct {
}

func (t *ThisAuthenticator) This() AuthenticatorIOCInterface {
	thisPtr, _ := GetAuthenticatorIOCInterfaceSingleton()
	return thisPtr
}
